// packages/react-todo/src/components/todo.jsx
import React, { useState } from "react";
import avatar from "../assets/myAvatar.png";
import moment from "moment";
import TodoModal from "./modals/todoModal";

function Todo({ todo }) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <div
        className="border border-gray-300 border-t-0 w-9/12 mx-auto hover:bg-blue-600 hover:text-white mb-5 p-2 shadow-2xl rounded-lg"
        onClick={() => {
          setIsModalOpen(isModalOpen ? false : true);
        }}
      >
        <div className="container flex flex-row h-10 text-start justify-between pl-6">
          <h5 className="font-semibold ">{todo.name}</h5>
          <div className="w-12">
            <img src={avatar} className="w-full rounded-full" />
          </div>
        </div>
        <p className="text-start pl-6 text-gray-400 text-sm hover:text-gray-300">
          {moment(todo.updatedAt).fromNow()}
        </p>
      </div>
      <TodoModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        todoData={todo}
      />
    </>
  );
}

export default Todo;

// packages/svelte-todo/src/lib/components/Todo.svelte
<script lang="ts">
  import { formatRelative, subDays } from 'date-fns';
  import type { Todo } from '$lib/types';
  import { getUser } from '$lib/stores';

  export let todo: Todo;
</script>

<div class="flex flex-col p-5 m-4 rounded-md shadow-sm bg-white shadow-gray-400">
  <div class="text-left text-lg font-semibold">{todo.title}</div>
  <div class="flex flex-row">
    <span class="flex-1 basis-10/12 pt-5 text-sm"
      >{formatRelative(subDays(new Date(), 6), todo.createdAt)}</span
    >
    <span
      ><img
        class="inline-block h-10 w-10 rounded-full ring-2 ring-white"
        src={getUser(todo.user).avatar}
        alt="avatar"
      /></span
    >
  </div>
</div>
